//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Door
    {
        public int Id { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
    
        public virtual House House { get; set; }
        public virtual Room Room { get; set; }
    }
}
