//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.House = new HashSet<House>();
            this.Car = new HashSet<Car>();
            this.Cycle = new HashSet<Cycle>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<House> House { get; set; }
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<Cycle> Cycle { get; set; }
        public virtual Portfolio Portfolio { get; set; }
    }
}
