//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public Portfolio()
        {
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
