//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.Bloomberg.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PX_BID")]
        public string Bloomberg_Field_Bid {
            get {
                return ((string)(this["Bloomberg_Field_Bid"]));
            }
            set {
                this["Bloomberg_Field_Bid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PX_ASK")]
        public string Bloomberg_Field_Ask {
            get {
                return ((string)(this["Bloomberg_Field_Ask"]));
            }
            set {
                this["Bloomberg_Field_Ask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAST_UPDATE_BID_RT")]
        public string Bloomberg_Field_LastUpdateBid {
            get {
                return ((string)(this["Bloomberg_Field_LastUpdateBid"]));
            }
            set {
                this["Bloomberg_Field_LastUpdateBid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAST_UPDATE_ASK_RT")]
        public string Bloomberg_Field_LastUpdateAsk {
            get {
                return ((string)(this["Bloomberg_Field_LastUpdateAsk"]));
            }
            set {
                this["Bloomberg_Field_LastUpdateAsk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TIME")]
        public string Bloomberg_Field_Time {
            get {
                return ((string)(this["Bloomberg_Field_Time"]));
            }
            set {
                this["Bloomberg_Field_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reason")]
        public string Bloomberg_Name_Reason {
            get {
                return ((string)(this["Bloomberg_Name_Reason"]));
            }
            set {
                this["Bloomberg_Name_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exceptions")]
        public string Bloomberg_Name_Exceptions {
            get {
                return ((string)(this["Bloomberg_Name_Exceptions"]));
            }
            set {
                this["Bloomberg_Name_Exceptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("category")]
        public string Bloomberg_Name_Category {
            get {
                return ((string)(this["Bloomberg_Name_Category"]));
            }
            set {
                this["Bloomberg_Name_Category"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("description")]
        public string Bloomberg_Name_Description {
            get {
                return ((string)(this["Bloomberg_Name_Description"]));
            }
            set {
                this["Bloomberg_Name_Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fieldId")]
        public string Bloomberg_Name_FieldId {
            get {
                return ((string)(this["Bloomberg_Name_FieldId"]));
            }
            set {
                this["Bloomberg_Name_FieldId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ServiceOpened")]
        public string Bloomberg_Name_ServiceOpened {
            get {
                return ((string)(this["Bloomberg_Name_ServiceOpened"]));
            }
            set {
                this["Bloomberg_Name_ServiceOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SessionStarted")]
        public string Bloomberg_Name_SessionStarted {
            get {
                return ((string)(this["Bloomberg_Name_SessionStarted"]));
            }
            set {
                this["Bloomberg_Name_SessionStarted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("source")]
        public string Bloomberg_Name_Source {
            get {
                return ((string)(this["Bloomberg_Name_Source"]));
            }
            set {
                this["Bloomberg_Name_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("errorCode")]
        public string Bloomberg_Name_ErrorCode {
            get {
                return ((string)(this["Bloomberg_Name_ErrorCode"]));
            }
            set {
                this["Bloomberg_Name_ErrorCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subcategory")]
        public string Bloomberg_Name_Subcategory {
            get {
                return ((string)(this["Bloomberg_Name_Subcategory"]));
            }
            set {
                this["Bloomberg_Name_Subcategory"] = value;
            }
        }
    }
}
