//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class DoorModel : NotificationObject
    {
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
        private short width;
    	public short Width 
    	{ 
    		get { return width; } 
    		set { width = value; RaisePropertyChanged(() => Width); } 
    	} 
    
        private short height;
    	public short Height 
    	{ 
    		get { return height; } 
    		set { height = value; RaisePropertyChanged(() => Height); } 
    	} 
    
    
        public virtual HouseModel House { get; set; }
        public virtual RoomModel Room { get; set; }
    }
}
