//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class HouseModel : NotificationObject
    {
        public HouseModel()
        {
            this.Room = new HashSet<RoomModel>();
            this.Address = new AddressTypeModel();
        }
    
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
    
        public AddressTypeModel Address { get; set; }
    
        public virtual DoorModel Door { get; set; }
        public virtual ICollection<RoomModel> Room { get; set; }
        public virtual PersonModel Owner { get; set; }
    }
}
