//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class PersonModel : NotificationObject
    {
        public PersonModel()
        {
            this.House = new HashSet<HouseModel>();
            this.Car = new HashSet<CarModel>();
            this.Cycle = new HashSet<CycleModel>();
        }
    
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
        private string name;
    	public string Name 
    	{ 
    		get { return name; } 
    		set { name = value; RaisePropertyChanged(() => Name); } 
    	} 
    
    
        public virtual ICollection<HouseModel> House { get; set; }
        public virtual ICollection<CarModel> Car { get; set; }
        public virtual ICollection<CycleModel> Cycle { get; set; }
        public virtual PortfolioModel Portfolio { get; set; }
    }
}
