//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Brand = "BMW";
            this.Tires = new HashSet<Tire>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public int Bhp { get; set; }
    
        public virtual ICollection<Tire> Tires { get; set; }
        public virtual Person Owner { get; set; }
    }
}
