//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public Nullable<decimal> Bid { get; set; }
        public Nullable<decimal> Ask { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
