//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Door = new HashSet<Door>();
        }
    
        public int Id { get; set; }
        public string Size { get; set; }
    
        public virtual House House { get; set; }
        public virtual ICollection<Door> Door { get; set; }
    }
}
