//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.Price = new HashSet<Price>();
        }
    
        public int Id { get; set; }
        public string Ticker { get; set; }
        public int Valor { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual ICollection<Price> Price { get; set; }
    }
}
