//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TweakTestDataEntities : DbContext
    {
        public TweakTestDataEntities()
            : base("name=TweakTestDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> CarSet { get; set; }
        public DbSet<Tire> TireSet { get; set; }
        public DbSet<House> HouseSet { get; set; }
        public DbSet<Door> DoorSet { get; set; }
        public DbSet<Cycle> CycleSet { get; set; }
        public DbSet<Lock> LockSet { get; set; }
        public DbSet<Room> RoomSet { get; set; }
        public DbSet<Person> PersonSet { get; set; }
        public DbSet<Stock> StockSet { get; set; }
        public DbSet<Portfolio> PortfolioSet { get; set; }
        public DbSet<Price> PriceSet { get; set; }
    
        public virtual ObjectResult<Car> StoredProcedure1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Car>("StoredProcedure1");
        }
    
        public virtual ObjectResult<Car> StoredProcedure1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Car>("StoredProcedure1", mergeOption);
        }
    }
}
