//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class CycleModel : NotificationObject
    {
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
        private short gears;
    	public short Gears 
    	{ 
    		get { return gears; } 
    		set { gears = value; RaisePropertyChanged(() => Gears); } 
    	} 
    
    
        public virtual LockModel Lock { get; set; }
        public virtual PersonModel Owner { get; set; }
    }
}
