//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class PortfolioModel : NotificationObject
    {
        public PortfolioModel()
        {
            this.Stock = new HashSet<StockModel>();
        }
    
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
    
        public virtual PersonModel Person { get; set; }
        public virtual ICollection<StockModel> Stock { get; set; }
    }
}
