//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class StockModel : NotificationObject
    {
        public StockModel()
        {
            this.Price = new HashSet<PriceModel>();
        }
    
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
        private string ticker;
    	public string Ticker 
    	{ 
    		get { return ticker; } 
    		set { ticker = value; RaisePropertyChanged(() => Ticker); } 
    	} 
    
        private int valor;
    	public int Valor 
    	{ 
    		get { return valor; } 
    		set { valor = value; RaisePropertyChanged(() => Valor); } 
    	} 
    
    
        public virtual PortfolioModel Portfolio { get; set; }
        public virtual ICollection<PriceModel> Price { get; set; }
    }
}
