//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakToolkit.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Practices.Prism.ViewModel;
    
    public partial class TireModel : NotificationObject
    {
        private int id;
    	public int Id 
    	{ 
    		get { return id; } 
    		set { id = value; RaisePropertyChanged(() => Id); } 
    	} 
    
        private short dimension;
    	public short Dimension 
    	{ 
    		get { return dimension; } 
    		set { dimension = value; RaisePropertyChanged(() => Dimension); } 
    	} 
    
    
        public virtual CarModel Car { get; set; }
    }
}
